alias pmv='/mnt/c/Users/James/documents/aaRS-pipeline/resources/mgltools_x86_64Linux2_1.5.6/bin/pmv'
alias adt='/mnt/c/Users/James/documents/aaRS-pipeline/resources/mgltools_x86_64Linux2_1.5.6/bin/adt'
alias vision='/mnt/c/Users/James/documents/aaRS-pipeline/resources/mgltools_x86_64Linux2_1.5.6/bin/vision'
alias cadd='/mnt/c/Users/James/documents/aaRS-pipeline/resources/mgltools_x86_64Linux2_1.5.6/bin/cadd'
alias pythonsh='/mnt/c/Users/James/documents/aaRS-pipeline/resources/mgltools_x86_64Linux2_1.5.6/bin/pythonsh'
